### ISSUE TITLE
Call to private method CloudflareBypass\RequestMethod\Stream::getHeader() 

### ISSUE THREAD

**Issue by yylzcom** [jaymoulin/guzzlehttp-cloudflare#4]
**Description**

When try to use with latest CloudflareBypass from Karyna's latest version.

**Version you are using (you may find this information in your `composer.lock` file)**
"kyranrana/cloudflare-bypass": "^v2.0",
 "jaymoulin/guzzlehttp-cloudflare": "^0.2.0"

```
 Uncaught Error: Call to private method CloudflareBypass\RequestMethod\Stream::getHeader() from context 'GuzzleCloudflare\Middleware' in /var/www/fetch/vendor/jaymoulin/guzzlehttp-cloudflare/src/Middleware.php:116
Stack trace:
#0 /var/www/fetch/vendor/jaymoulin/guzzlehttp-cloudflare/src/Middleware.php(69): GuzzleCloudflare\Middleware->hackRequest(Object(GuzzleHttp\Psr7\Request))
#1 /var/www/fetch/vendor/jaymoulin/guzzlehttp-cloudflare/src/Middleware.php(54): GuzzleCloudflare\Middleware->checkResponse(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), Array)
#2 /var/www/fetch/vendor/guzzlehttp/promises/src/FulfilledPromise.php(39): GuzzleCloudflare\Middleware->GuzzleCloudflare\{closure}(Object(GuzzleHttp\Psr7\Response))
#3 /var/www/fetch/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}()
#4 /var/www/fetch/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /var/www/fetch/vendor/guzzlehttp/p in /var/www/fetch/vendor/jaymoulin/guzzlehttp-cloudflare/src/Middleware.php on line 116
```

**Comment by KyranRana** [comment]
Note to the owner. Just replace `getHeader` with `getRequestHeader` 

A good place to look for public methods you can use is Base/RequestMethod/RequestMethod.php

Love what you done here by the way. great work @jaymoulin

**Comment by jaymoulin** [comment]
@KyranRana Thank you for your message and fixing the bug :smile: (even though you introduced it :rofl: )
